name: Build and publish
on:
  push:
    tags:
      - "*"
  release:
    types: [ created ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@latest
      - run: mkdir installer
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@latest
        with:
          node-version: [20.x]
      - name: Build
        run: |
          npm i
          npm i --save-dev archiver
          node archiver.js
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rutube-downloader.zip
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true